### ISSUE TITLE
Error communicating with GitHub

### ISSUE THREAD

**Issue by theocincotta** [getsentry/sentry-github#12]
I'm getting this error when I try to open a ticket with Github. Any idea what I'm doing wrong?

Error creating issue: [u'Error communicating with GitHub: Not Found']

Thanks!

**Comment by jmagnusson** [comment]
How does one configure the scope if one is paying for your hosted version? Can't get issue creation to work for my private organization...

**Comment by dcramer** [comment]
@jmagnusson its automatically configured for you and should include private repos. Are oyu seeing that not to be true?

**Comment by jmagnusson** [comment]
It seems like Sentry is asking for access in my public repo, but we've enabled [https://github.com/organizations/hestra/settings/oauth_application_policy](Third-party application access policy) in our organization, which might be what's causing it. Sentry is not in this list.

**Comment by dcramer** [comment]
You can reauthorize it which will allow you to enable that access. I believe there's also options somewhere to do it after the fact.

**Comment by jmagnusson** [comment]
How do I reauthorize it? (I use getsentry.com)

I've done the following:
1. Disabled the integration on all my Sentry projects
2. Revoked access for Sentry in Github (only my private profile had access to Sentry)
3. Re-enabled the Github integration for one of my projects (no authorization redirect, re-enabled really quickly)
4. Tried "Create Github issue"
5. Got `Error creating issue: [u'Error communicating with GitHub: Bad credentials']`

This happens on both your beta version and the regular.

**Comment by dcramer** [comment]
@jmagnusson did you try reauthorizing via account settings? Account => Identities => Disconnect

**Comment by jmagnusson** [comment]
That worked. Thanks!

Btw, do you really need to have read+write permissions on the following to be able to post an issue on the user's behalf?

* Code
* Issues
* Pull requests
* Wikis
* Settings
* Webhooks and services
* Deploy keys

Should be enough for you with Write permission on Issue, or am I missing something?

**Comment by dcramer** [comment]
@jmagnusson I believe this is legacy as GitHub didn't use to have complex scopes. It's likely we just need to determine what makes sense today.

**Comment by jmagnusson** [comment]
Okay, thanks.
