### ISSUE TITLE
Issues with understanding readme

### ISSUE THREAD

**Issue by vinitkumar** [getsentry/sentry-github#16]
This is from the readme.

You'll have to create an application in GitHub to get the app ID and API secret. Use the following for the Authentication redirect URL::

    <URL_TO_SENTRY>/account/settings/social/complete/github/

What is the URL_TO_SENTRY here? Is it DSN or something else?

Ensure you've configured GitHub auth in Sentry::

    GITHUB_APP_ID = 'GitHub Application Client ID'
    GITHUB_API_SECRET = 'GitHub Application Client Secret'
    GITHUB_EXTENDED_PERMISSIONS = ['repo']

Also, where does these need to be added? In my Django app settings file? I couldn't find any place in the sentry to add it. If there is any such place please guide me. 

Thanks.

**Comment by seocam** [comment]
@vinitkumar all settings should be added to sentry settings file (usually `sentry-config.py`).

The URL_TO_SENTRY is the url to sentry :)
For example: `http://sentry.example.com` or `http://sentry.yourcompany.com`

Actually the instructions seams fine to me.

**Comment by dcramer** [comment]
This is specifically documentation for people installing the plugin, not user facing documentation. If you have specific suggestions that would improve it feel free to propose, but IMO its very clear.
