### ISSUE TITLE
Doesn't support oauth2 authorization to organization

### ISSUE THREAD

**Issue by frankamp** [getsentry/sentry-github#19]
It is attempting to associate with my user account instead. You should be able to supply an organization.

**Comment by dcramer** [comment]
AFAIK this is a limitation of the GitHub API. There's no way (that's clear to me) to restrict access to a single organization. Feel free to re-open if that's not true.

**Comment by frankamp** [comment]
Thanks. I worked around this by logging out of github first, and then going through the authorization flow by logging in with an institutional/system/machine user that's associated solely with our organization's github account for automation purposes.

That way it isn't tied to a human, and things won't break or adjust when people flow in and out of the team.
