### ISSUE TITLE
Can't see the "Login with Github" after upgrading Sentry

### ISSUE THREAD

**Issue by seocam** [getsentry/sentry-github#21]
I was running Sentry 6.4.4 and upgraded to 7.7.0. After the upgrade the link "Login with Github" disappeared from the Login screen.

**Comment by dcramer** [comment]
This feature was removed in newer versions of Sentry due to compatibility and deprecation of APIs.

**Comment by seocam** [comment]
@dcramer any plans to re-add it? This was really useful...

**Comment by dcramer** [comment]
No. It's replaced by our internal SSO framework.

Social auth was purely a "lazy login" shortcut and didn't actually provide much usefulness. i.e. it didn't manage membership etc.
