### ISSUE TITLE
command not found: GITHUB_APP_ID

### ISSUE THREAD

**Issue by trkrameshkumar** [getsentry/sentry-github#22]
Hi,

After installing 
`pip install sentry-github`

when i tried to set 
`GITHUB_APP_ID = 'ABCD123'`
i have got this error `zsh: command not found: GITHUB_APP_ID` on terminal

**Comment by dcramer** [comment]
@trkrameshkumar you need to set that in your sentry configuration file

**Comment by trkrameshkumar** [comment]
@dcramer thanks for your reply, but what is the location of the sentry configuration file, and what is the file structure?

**Comment by trkrameshkumar** [comment]
@dcramer ?

**Comment by trkrameshkumar** [comment]
@dcramer are you refering to sentry.rb in config(in rails application) folder?

**Comment by dcramer** [comment]
@trkrameshkumar if you're using getsentry.com you dont need to do anything -- this is only for running against self-hosted Sentry

**Comment by trkrameshkumar** [comment]
@dcramer Ohh, Ok, Yes we are using only getsentry.com, there is no clear documentation on how to integrate githuhb with getsentry.com for the purpose of  create issues on github for evens happens on gesentry, if you guide me on how to integrated my github repo with  getsentry that will be greatly appreciated.

**Comment by dcramer** [comment]
@trkrameshkumar visit your project settings => issue tracking => click github. Once configured you can more easily create GitHub issues by visiting a Sentry issue => click more => click create github issue

**Comment by trkrameshkumar** [comment]
@dcramer i get that , i can able to create issues in this way, i am asking about automatic github issues for every event, is that possible ?

**Comment by dcramer** [comment]
It is not, and realistically it doesnt make a lot of sense. You wouldn't want to flood your GitHub issue tracker if you had a lot of errors, and you wouldn't want to create duplicate errors if Sentry re-hashed events

**Comment by trkrameshkumar** [comment]
Fair point, i really appreciate your quick reply, Thanks for your help @dcramer
