### ISSUE TITLE
Use `sentry-github` with `sentry-auth-github`

### ISSUE THREAD

**Issue by mitchhentges** [getsentry/sentry-github#24]
`sentry-github` needs my GitHub application's callback to be `<URL_TO_SENTRY>/account/settings/social/complete/github/`, while `sentry-auth-github` requires it to simply be `<URL_TO_SENTRY>`. So, I need two separate GitHub applications.

However, both integrations use the same configuration parameters for the GitHub application: `GITHUB_APP_ID` and `GITHUB_API_SECRET`. So, I can only specify one application.

Can I only use one integration, or the other? That would be a bummer

**Comment by dcramer** [comment]
You should be able to set the callback URL to the base. e.g.: https://app.getsentry.com
