### ISSUE TITLE
Allow an existing GitHub Issue to be linked to a Sentry error

### ISSUE THREAD

**Issue by wrobbinz** [getsentry/sentry-github#26]
**Problem:** Currently, the sentry/github integration allows for a user to create a GH issue from the page of a sentry error. However, if an issue has already been created, there appears to be no elegant way to link the sentry error with the existing issue. The workaround is to create a separate issue via the Sentry error page, then copy/paste issue text over to new ticket. Another workaround is to create a comment with a hyperlink to the GH issue.

**Solution:** On the sentry error page, user can click a button to input an issue number that will then associate the Sentry error with the GH issue.

**Comment by popmonkey** [comment]
would also love this feature

**Comment by wrobbinz** [comment]
Well shit homie, you guys nailed it. 👍
