### ISSUE TITLE
Can't create issues in github enterprise instance

### ISSUE THREAD

**Issue by databus23** [getsentry/sentry-github#27]
I'm having problems making this work against our GHE.

I'm using sentry 8.3.3 on-premise with SSO and this plugin configured against our GHE instance:

```
GITHUB_APP_ID = os.environ.get('GITHUB_APP_ID')
GITHUB_API_SECRET = os.environ.get('GITHUB_API_SECRET')
GITHUB_BASE_DOMAIN = "github.internal.corp"
GITHUB_API_DOMAIN = "github.internal.corp/api/v3"
GITHUB_EXTENDED_PERMISSIONS = ['repo']
SOCIAL_AUTH_REDIRECT_IS_HTTPS = True
USE_X_FORWARDED_HOST = True
```

As suggested in #24 I set up the OAuth callback to the sentry base url.

The problem I'm seeing is that the users logging in via SSO have no identity associated.
Trying to create an issue gives the error `You still need to associate an identity with GitHub before you can create issues with this service.`
When I click in the github link on Account->Identities it takes me to github.com which responds with a 404 because it doesn't know the `GITHUB_APP_ID`

Any suggestions on how to fix this? Is this supposed to work?

**Comment by dcramer** [comment]
You'd definitely need to associate multiple identities. The GitHub issue extension (this repo) isn't as mature as our SSO provider, so it's very possible that GHE support simply isn't working well. We use ``django-social-auth`` which is an old framework for identifying there at this time, so it's also possible its just a misconfiguration.

**Comment by tvon** [comment]
FWIW, I ran across the identity issue as well.  Sentry is [pinned to django-social-auth 7.x](https://github.com/getsentry/sentry/blob/8.5.1/setup.py#L101), and that version [hard-codes the important GitHub URLs](https://github.com/omab/django-social-auth/blob/v0.7.28/social_auth/backends/contrib/github.py#L35-L38).

**Comment by QingsongYao** [comment]
I have a fix for this and will send PR soon. Together with another fix for  github_plugin, End to end support with Github enterprise SSO and issue link should be ready.

**Comment by johnbellone** [comment]
@QingsongYao Did that PR ever land?

**Comment by QingsongYao** [comment]
No.  it is pending at https://github.com/getsentry/sentry-plugins/pull/208

**Comment by bharathrajbk** [comment]
Why was https://github.com/getsentry/sentry-github/pull/23/files reverted?

**Comment by bharathrajbk** [comment]
Can we please get this issue addressed? Our organization needs this on priority!

**Comment by dcramer** [comment]
This repository is no longer used and we will be adding GHE support sometime in Q2.
