### ISSUE TITLE
Auto close exceptions in sentry when the linked github issue is closed

### ISSUE THREAD

**Issue by tomschlick** [getsentry/sentry-github#41]
It could use webhooks to do this if we had an endpoint to point them to.

**Comment by dcramer** [comment]
@tomschlick the reason we don't do this yet is because resolving an issue in sentry means "its fixed right now in and wont happen again". We'd want to tie it into commits and say "when this commit is live, its fixed".

**Comment by tomschlick** [comment]
Ah good point. Github has a deployments api that might help there although it isn't very widely used yet from what I have seen.

**Comment by dcramer** [comment]
@tomschlick unreleased we have what we call short IDs in Sentry, and our near-term goal is to be able to reference those in commits to deal with auto resolution.

**Comment by tomschlick** [comment]
👍
