### ISSUE TITLE
Can't create issues on github.

### ISSUE THREAD

**Issue by vinitkumar** [getsentry/sentry-github#42]
Every time I try to create an issue on github using the option in sentry. I get the error in the screenshot. What is the way to fix/debug/reason about this problem?

![screen shot 2016-10-26 at 12 35 04 pm](https://cloud.githubusercontent.com/assets/537678/19716323/c6a75cac-9b78-11e6-8877-3840e4f541c7.png)

**Comment by dcramer** [comment]
@vinitkumar its possibly in the logs, but also good chance thats not true. That said, Sentry 8.10 we're moving away from this plugin entirely, and you'll be able to just ship `sentry-plugins`, which has a new version of this integration. That'll be released early Nov.

(If this is actually on sentry.io, let us know, as we can debug it there)

**Comment by vinitkumar** [comment]
@dcramer Actually it is on sentry.io Let me know what details you would require. I will be happy to provide them.

**Comment by dcramer** [comment]
@vinitkumar mind pinging david at with your account name/email address and I should (hopefully) be able to search on it

**Comment by vinitkumar** [comment]
@dcramer Sorry for the delay in response. How do I ping david? Should I contact support support@getsentry.com ?

**Comment by vinitkumar** [comment]
@dcramer I am happy to inform you that it no longer gives error while creating issues on github. It just works magically. 

Also, thanks for building such a fantastic service. We love sentry and it has made our app much more stable and better. Cheers 🍻

**Comment by dcramer** [comment]
Good to hear. We generally actively address issues that show up and have been overhauling some of our key integrations lately.
