### ISSUE TITLE
Doesn't seem to work with private repos because there is no "organization"

### ISSUE THREAD

**Issue by friday** [getsentry/sentry-github#44]
Github accounts can use private repos with a username rather than an organization. Then you can't integrate it seems.

![screen shot 2017-04-30 at 17 00 33](https://cloud.githubusercontent.com/assets/515120/25565445/e37eccd0-2dc6-11e7-82df-68f1737c791c.png)

**Comment by dcramer** [comment]
This repo is deprecated and the feature you're talking about is SSO which is only bound to organizations

**Comment by friday** [comment]
Sorry!
