### ISSUE TITLE
The 'Access-Control-Allow-Origin' header has a value 'https://example.herokuapp.com/' that is not equal to the supplied origin.

### ISSUE THREAD

**Issue by sendreagheorghe** [getsentry/sentry-github#46]
I have deployed 2 applications on heroku back-end (node js) and front-end (angular 5).
    

- Back-end domain (B):  **https://talkwithme-app.herokuapp.com/call/**

- Front-end domain (F): **https://talkwith-me.herokuapp.com/registration**

First I have a question for you guys is it possible to make B accessible only for F?

I tried many adding **cors** package but it doesn't work.

After that i added some headers
`
app.use((req, res, next) => {

        res.header("Access-Control-Allow-Origin",  config.front_end.app_url);

        res.header("Access-Control-Allow-Headers", 'Origin,X-Requested-With,Content- 
        Type,Accept,content-type,application/json');

        res.header('Access-Control-Allow-Methods', 'GET,PUT,POST,DELETE,OPTIONS');
        res.header("Access-Control-Allow-Credentials", true);

        next();
    });
`

config.front_end.app_url = https://talkwith-me.herokuapp.com/registration.

But when trying to make a request i get an error

![image](https://user-images.githubusercontent.com/20684849/51532917-1b8ab880-1e4a-11e9-9a0e-47a2d4ea5b7e.png)

**Comment by sendreagheorghe** [comment]
Found the issue. This solution works greate.
Issue was my config.front_end.app_url was  https://talkwith-me.herokuapp.com/registration/ so the las '/' broke my headers

**Comment by Camiloagudelo4368** [comment]
Add this url before "https://cors-anywhere.herokuapp.com/"
So your url will be something like: 
"https://cors-anywhere.herokuapp.com/https://talkwith-me.herokuapp.com/registration"
